{
  "result": "compile_failed",
  "message": "/tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:67:5: error: redeclaration of enumerator 'UTASSERT_CASETYPE_PASS'\n   67 |     UTASSERT_CASETYPE_PASS = 0,\n      |     ^~~~~~~~~~~~~~~~~~~~~~\nIn file included from /tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:41:\n/tmp/tmp69fsnr8u/src/ut_assert/inc/utassert.h:86:5: note: previous definition of 'UTASSERT_CASETYPE_PASS' with type 'enum <anonymous>'\n   86 |     UTASSERT_CASETYPE_PASS,    /**< Test case passed (normal) status messages */\n      |     ^~~~~~~~~~~~~~~~~~~~~~\n/tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:68:5: error: redeclaration of enumerator 'UTASSERT_CASETYPE_FAILURE'\n   68 |     UTASSERT_CASETYPE_FAILURE = 1,\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~\nIn file included from /tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:41:\n/tmp/tmp69fsnr8u/src/ut_assert/inc/utassert.h:77:5: note: previous definition of 'UTASSERT_CASETYPE_FAILURE' with type 'enum <anonymous>'\n   77 |     UTASSERT_CASETYPE_FAILURE, /**< Test case failure status messages */\n      |     ^~~~~~~~~~~~~~~~~~~~~~~~~\n/tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:69:5: error: redeclaration of enumerator 'UTASSERT_CASETYPE_MAX'\n   69 |     UTASSERT_CASETYPE_MAX = 2\n      |     ^~~~~~~~~~~~~~~~~~~~~\nIn file included from /tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:41:\n/tmp/tmp69fsnr8u/src/ut_assert/inc/utassert.h:89:5: note: previous definition of 'UTASSERT_CASETYPE_MAX' with type 'enum <anonymous>'\n   89 |     UTASSERT_CASETYPE_MAX      /**< Reserved value, No messages should be used with this */\n      |     ^~~~~~~~~~~~~~~~~~~~~\n/tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:126:6: error: conflicting types for 'UtAssert_DoReport'; have 'void(const char *, uint32,  uint32,  uint32,  UtAssert_CaseType_t,  unsigned int,  const char *)' {aka 'void(const char *, unsigned int,  unsigned int,  unsigned int,  UtAssert_CaseType_t,  unsigned int,  const char *)'}\n  126 | void UtAssert_DoReport(const char *File, uint32 Line, uint32 TestSegmentCount,\n      |      ^~~~~~~~~~~~~~~~~\nIn file included from /tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:41:\n/tmp/tmp69fsnr8u/src/ut_assert/inc/utassert.h:973:6: note: previous declaration of 'UtAssert_DoReport' with type 'void(const char *, uint32,  uint32,  uint32,  uint8,  const char *, const char *)' {aka 'void(const char *, unsigned int,  unsigned int,  unsigned int,  unsigned char,  const char *, const char *)'}\n  973 | void UtAssert_DoReport(const char *File, uint32 LineNum, uint32 SegmentNum, uint32 SegmentSeq, uint8 MessageType,\n      |      ^~~~~~~~~~~~~~~~~\n/tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c: In function 'UtAssert_GetCaseTypeAbbrev':\n/tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:315:9: error: duplicate case value\n  315 |         case UTASSERT_CASETYPE_FAILURE:\n      |         ^~~~\n/tmp/tmp69fsnr8u/src/ut_assert/src/utassert.c:312:9: note: previously used here\n  312 |         case UTASSERT_CASETYPE_ABORT:\n      |         ^~~~\ngmake[2]: *** [ut_assert/CMakeFiles/ut_assert.dir/build.make:76: ut_assert/CMakeFiles/ut_assert.dir/src/utassert.c.o] Error 1\ngmake[1]: *** [CMakeFiles/Makefile2:788: ut_assert/CMakeFiles/ut_assert.dir/all] Error 2\ngmake: *** [Makefile:146: all] Error 2"
}